const COMPANIES = [
  { name: "Rosemary Villas", status: "Active", detail: "File Auditor v3", href: "#files" },
  { name: "CRA Construction", status: "Queued", detail: "Accounting next", href: "/cra" },
  { name: "Site Development Services", status: "Planned", detail: "", href: "#companies" },
];

export default function Home() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: "rgb(245, 241, 234)", color: "rgb(26, 31, 28)" }}>
      <main className="mx-auto max-w-6xl px-4 py-10 sm:px-6">
        <section className="rounded-2xl border p-6" style={{ backgroundColor: "rgba(255,255,255,0.65)", borderColor: "rgba(90,138,94,0.25)" }}>
          <h1 className="text-2xl font-semibold">Executive Status</h1>
          <p className="mt-2" style={{ color: "rgba(26,31,28,0.7)" }}>Operating view across Alberius holdings.</p>
          <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {COMPANIES.map((item) => (
              <a key={item.name} href={item.href} className="rounded-xl border p-5 transition-colors hover:border-green-900/50" style={{ backgroundColor: "rgba(255,255,255,0.72)", borderColor: "rgba(90,138,94,0.25)" }}>
                <div className="text-lg font-semibold">{item.name}</div>
                <div className="mt-2 text-sm" style={{ color: "rgb(90,138,94)" }}>{item.status}</div>
                {item.detail ? <div className="mt-1 text-sm" style={{ color: "rgba(26,31,28,0.7)" }}>{item.detail}</div> : null}
              </a>
            ))}
          </div>
        </section>

        <section id="files" className="mt-10 rounded-2xl border p-6" style={{ backgroundColor: "rgba(255,255,255,0.65)", borderColor: "rgba(90,138,94,0.25)" }}>
          <h2 className="text-xl font-semibold">Files & Records</h2>
          <p className="mt-2 text-sm" style={{ color: "rgba(26,31,28,0.7)" }}>Module status: active. Latest auditor output for active shared drives.</p>
          <div className="mt-6 grid gap-4 sm:grid-cols-3">
            <div className="rounded-xl border p-5" style={{ backgroundColor: "rgba(255,255,255,0.72)", borderColor: "rgba(90,138,94,0.25)" }}>
              <div>Latest Report</div>
              <div className="mt-1 text-sm" style={{ color: "rgba(26,31,28,0.7)" }}>reports/latest/dashboard.html</div>
            </div>
            <div className="rounded-xl border p-5" style={{ backgroundColor: "rgba(255,255,255,0.72)", borderColor: "rgba(90,138,94,0.25)" }}>
              <div>Executive Summary</div>
              <div className="mt-1 text-sm" style={{ color: "rgba(26,31,28,0.7)" }}>reports/latest/executive_summary.md</div>
            </div>
            <div className="rounded-xl border p-5" style={{ backgroundColor: "rgba(255,255,255,0.72)", borderColor: "rgba(90,138,94,0.25)" }}>
              <div>Issues Queue</div>
              <div className="mt-1 text-sm" style={{ color: "rgba(26,31,28,0.7)" }}>reports/latest/issues.csv</div>
            </div>
          </div>
          <p className="mt-4 text-sm" style={{ color: "rgba(26,31,28,0.7)" }}>
            The full dashboard is generated by the local Storage Auditor. It is not hosted in this repo yet because the report outputs are large and change on every scan.
          </p>
        </section>

        <section id="companies" className="mt-10 rounded-2xl border p-6" style={{ backgroundColor: "rgba(255,255,255,0.65)", borderColor: "rgba(90,138,94,0.25)" }}>
          <h2 className="text-xl font-semibold">Companies</h2>
          <p className="mt-2 text-sm" style={{ color: "rgba(26,31,28,0.7)" }}>Company configuration used by the hub.</p>
          <pre className="mt-4 overflow-x-auto rounded-xl border p-4 text-sm" style={{ backgroundColor: "rgba(255,255,255,0.72)", borderColor: "rgba(90,138,94,0.25)", color: "rgb(26,31,28)" }}>
{`[
  { "id": "rosemary-villas", "name": "Rosemary Villas at Chenal", "active": true },
  { "id": "cra-construction", "name": "CRA Construction", "active": false },
  { "id": "site-development-services", "name": "Site Development Services", "active": false }
]`}
          </pre>
        </section>

        <p className="mt-10 text-center text-sm" style={{ color: "rgba(26,31,28,0.55)" }}>
          Read-only by default. No company files are edited from this hub unless explicitly approved and implemented.
        </p>
      </main>
    </div>
  );
}
